---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: liatrio
resources:
- ../../base
nameSuffix: -lab
images:
- name: calebherbisonliatrio.azurecr.io/api
  newTag: latest