name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Azure Container Registry Build
      uses: Azure/acr-build@v1
      with:
        service_principal: bd7a7579-d80a-42dc-a938-bb96d95d625b
        service_principal_password: ${{ secrets.AZURE_CONTAINER_REGISTRY_CLIENT_SECRET }}
        tenant: 9e55f92d-d39e-4887-ac93-2c08a450261a
        registry: calebherbisonliatrio
        repository: liatrio
        image: api
        branch: main
        tag: latest
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_GITHUB_ACTIONS_CREDENTIALS }}'
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az aks get-credentials -n lab-0 -g lab-0
    - name: kubectl CLI
      uses: imajeetyadav/kubectl@v1
      with:
        version: v1.25.3
    - run: kubectl rollout restart deployment/api-lab -n liatrio
