name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Azure Container Registry Build
      uses: Azure/acr-build@v1
      with:
        service_principal: bd7a7579-d80a-42dc-a938-bb96d95d625b
        service_principal_password: ${{ secrets.AZURE_CONTAINER_REGISTRY_CLIENT_SECRET }}
        tenant: 9e55f92d-d39e-4887-ac93-2c08a450261a
        registry: calebherbisonliatrio
        repository: liatrio
        image: api
        branch: main
    - name: Deploy to lab
      uses: rmeneely/update-yaml@v1
      with:
        # The YAML file to be updated
        infile: ./kustomizations/overlays/lab/kustomization.yaml
        # Comma separated list of var=value
        varlist: newTag=GITHUB_SHA::8
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
